name = "bring-a-trailer-bot"
main = "index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "bring-a-trailer-bot"

[env.staging]
name = "bring-a-trailer-bot-staging"

# Environment variables will be set via wrangler secret
# wrangler secret put DISCORD_WEBHOOK_URL 